#!/bin/bash

set -e

CC=pgcc

GOSH=gosh
TOOLS_DIR="$(cd $(dirname $0) && pwd)"

LINT="$TOOLS_DIR/omni-lint.scm"
MACC_H="$TOOLS_DIR/macc.h"

if test -z "${OMNI_HOME}"; then
    echo 'Please set the environmental variable OMNI_HOME to point to the directory in which Omni Compiler is installed' >&2
    exit 1
fi

TEMP_DIR=$(mktemp -d)
C_FILE="${TEMP_DIR}/in.c"
TMP0="${TEMP_DIR}/0.c"
TMP1="${TEMP_DIR}/1.c"
TMP2="${TEMP_DIR}/2.i"
OUT="${TEMP_DIR}/out.xml"

cat > "${C_FILE}"
${GOSH} "${LINT}" < "${C_FILE}" >&2
${OMNI_HOME}/libexec/om_replace_pragma -I${OMNI_HOME}/include "${C_FILE}" -o "${TMP0}"
if [ "$1" = "-m" ]; then
    cat "${MACC_H}" "${TMP0}" > "${TMP1}"
else
    cat "${TMP0}" > "${TMP1}"
fi
${CC} -ta=tesla:managed -E -I${OMNI_HOME}/include -D_OPENACC=201111 "${TMP1}" > "${TMP2}"
${OMNI_HOME}/bin/C_Front --no-builtin-va-arg -facc -fopenmp "${TMP2}" -o "${OUT}"
cat "${OUT}"
rm -rf "${TEMP_DIR}"
